spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: snehal-authenticatio
          uri: lb://snehal-authentication
          predicates:
            - Path=/auth/**
        - id: harsh-dashboard
          uri: lb://snehal-dashboard
          predicates:
            - Path=/dashboard/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
server:
  port: 9093
eureka:
  instance:
    hostname: localhost